# Demo matrices

## rappels sur les vecteurs

In [1]:
x <- NULL

In [2]:
x

NULL

In [3]:
length(x)

[1] 0

In [4]:
1:100

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [5]:
print(1:100)

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100


In [6]:
print(50:100)

 [1]  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
[20]  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
[39]  88  89  90  91  92  93  94  95  96  97  98  99 100


In [7]:
length(1:100)

[1] 100

## matrices : 2 dimensions (lignes x colonnes)

1. création d'une matrice avec `matrix()`

In [8]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
          length 2 giving the row and column names respectively.  An
          empty list is treated as ‘NULL’, and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than ‘NULL’) ‘rownames’.  The default,
          ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
     infer it from the length of ‘data’ and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in ‘data’ to fill the matrix, then
     the elements in ‘data’ are recycled.  If ‘data’ has length zero,
     ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
     raw vectors) and ‘NULL’ for lists.

     ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
     attribute of length 2 and ‘FALSE’ otherwise.  Note that a
     ‘data.frame’ is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     ‘as.matrix’ is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying ‘as.vector’ to
     factors and ‘format’ to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     ‘is.matrix’ is a primitive function.

     The ‘print’ method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form ‘integer,7’ indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like

       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)
     
     will avoid duplicating ‘x’ _and_ preserve ‘class(x)’ which may be
     useful, e.g., for ‘Date’ objects.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘data.matrix’, which attempts to convert to a numeric matrix

In [9]:
matrix(1:10)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [10]:
print(matrix(1:10))

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


In [11]:
print(matrix(1:10, nrow=2, ncol=5))

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [12]:
print(matrix(1:10, nrow=2))

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [13]:
print(matrix(1:10, nrow=2, byrow=TRUE))

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


In [14]:
myData <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE)

In [15]:
myData

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [16]:
print(myData)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]   11   12   13


In [17]:
length(myData)

[1] 6

In [18]:
myData[3]

[1] 2

In [19]:
myData[5]

[1] 3

In [20]:
dim(myData)

[1] 2 3

In [21]:
print(dim(myData))

[1] 2 3


In [22]:
myData[1,3]

[1] 3

In [23]:
str(myData)

 num [1:2, 1:3] 1 11 2 12 3 13


In [24]:
newmatrix <- matrix(NA, 2,3)

In [25]:
newmatrix

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [26]:
newmatrix <- matrix(data=NA, nrow=2,ncol=3)

In [27]:
newmatrix

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [28]:
newmatrix <- matrix(data=NA, ncol=3,nrow=2)

In [29]:
newmatrix

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [30]:
newmatrix[1,3] <- "toto"

In [31]:
newmatrix

[,1] [,2] [,3]
[1,] NA   NA   toto
[2,] NA   NA   NA

In [32]:
newmatrix[,2] <- "titi"

In [33]:
newmatrix

[,1] [,2] [,3]
[1,] NA   titi toto
[2,] NA   titi NA

In [34]:
newmatrix[1,] <- rep(12,3)

In [35]:
newmatrix

[,1] [,2] [,3]
[1,] 12   12   12  
[2,] NA   titi NA

2. création de matrices à partir de vecteurs en utilisant `cbind()`, `rbind()`

In [37]:
load("../R1/anthropo.RData")

In [38]:
ls()

[1] "bmi"       "myData"    "newmatrix" "size"      "weight"    "x"

In [39]:
length(weight)

[1] 6

In [40]:
str(size)

 Named num [1:6] 1.75 1.8 1.65 1.9 1.74 1.91
 - attr(*, "names")= chr [1:6] "Fabien" "Pierre" "Sandrine" "Claire" ...


In [41]:
myData2 <- cbind(weight, size, bmi)

In [42]:
myData2

weight size bmi     
Fabien   60     1.75 19.59184
Pierre   72     1.80 22.22222
Sandrine 57     1.65 20.93664
Claire   90     1.90 24.93075
Bruno    95     1.74 31.37799
Delphine 72     1.91 19.73630

In [43]:
print(myData2)

         weight size      bmi
Fabien       60 1.75 19.59184
Pierre       72 1.80 22.22222
Sandrine     57 1.65 20.93664
Claire       90 1.90 24.93075
Bruno        95 1.74 31.37799
Delphine     72 1.91 19.73630


In [44]:
str(myData2)

 num [1:6, 1:3] 60 72 57 90 95 72 1.75 1.8 1.65 1.9 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:6] "Fabien" "Pierre" "Sandrine" "Claire" ...
  ..$ : chr [1:3] "weight" "size" "bmi"


In [45]:
myData3 <- rbind(weight, size, bmi)

In [46]:
myData3

Fabien   Pierre   Sandrine Claire   Bruno    Delphine
weight 60.00000 72.00000 57.00000 90.00000 95.00000 72.0000 
size    1.75000  1.80000  1.65000  1.90000  1.74000  1.9100 
bmi    19.59184 22.22222 20.93664 24.93075 31.37799 19.7363

In [47]:
t(myData3)

weight size bmi     
Fabien   60     1.75 19.59184
Pierre   72     1.80 22.22222
Sandrine 57     1.65 20.93664
Claire   90     1.90 24.93075
Bruno    95     1.74 31.37799
Delphine 72     1.91 19.73630

In [48]:
identical(t(myData3), myData2)

[1] TRUE

In [49]:
myData2["Fabien",]

weight     size      bmi 
60.00000  1.75000 19.59184

In [50]:
myData2[c("Claire", "Pierre"),]

weight size bmi     
Claire 90     1.9  24.93075
Pierre 72     1.8  22.22222

In [51]:
myData2[,"bmi"]

Fabien   Pierre Sandrine   Claire    Bruno Delphine 
19.59184 22.22222 20.93664 24.93075 31.37799 19.73630

In [52]:
myData2[,3]

Fabien   Pierre Sandrine   Claire    Bruno Delphine 
19.59184 22.22222 20.93664 24.93075 31.37799 19.73630

## opérations et fonctions sur les matrices

In [53]:
myData2

weight size bmi     
Fabien   60     1.75 19.59184
Pierre   72     1.80 22.22222
Sandrine 57     1.65 20.93664
Claire   90     1.90 24.93075
Bruno    95     1.74 31.37799
Delphine 72     1.91 19.73630

In [54]:
myData2*2

weight size bmi     
Fabien   120    3.50 39.18367
Pierre   144    3.60 44.44444
Sandrine 114    3.30 41.87328
Claire   180    3.80 49.86150
Bruno    190    3.48 62.75598
Delphine 144    3.82 39.47260

In [55]:
myData2[,2]*2

Fabien   Pierre Sandrine   Claire    Bruno Delphine 
    3.50     3.60     3.30     3.80     3.48     3.82

In [56]:
summary(myData2)

     weight           size            bmi       
 Min.   :57.00   Min.   :1.650   Min.   :19.59  
 1st Qu.:63.00   1st Qu.:1.742   1st Qu.:20.04  
 Median :72.00   Median :1.775   Median :21.58  
 Mean   :74.33   Mean   :1.792   Mean   :23.13  
 3rd Qu.:85.50   3rd Qu.:1.875   3rd Qu.:24.25  
 Max.   :95.00   Max.   :1.910   Max.   :31.38  

In [57]:
summary(weight)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  57.00   63.00   72.00   74.33   85.50   95.00 

In [58]:
mean(myData2)

[1] 33.08587

In [59]:
mean(myData2[,1])

[1] 74.33333