# __R Session n°2 - practical:__
M1 MEG UE5 - Claire Vandiedonck
***

__*Programme couvert:*__

- Les matrices et leur manipulation


---
    
**Rappels**    
> Les exercices proposés sont donnés dans un ordre progressif qui suit celui du diaporama associé. Ils ont des niveaux de difficulté variable. Pour chaque exercice, des fonctions R vous sont suggérées. N’hésitez pas à consulter leur menu d’aide en tapant soit `?nom_fonction`, soit `help(nom_fonction)`. Vous pouvez parvenir aux mêmes résultats avec d’autres commandes. Les commandes les plus courtes sont en général les meilleures. Une correction détaillée sera fournie.

> Vous pouvez réaliser ces exercices directement dans ce notebook sur `adenine` en indiquant votre code dans les cellules laissées libres. Pour ajouter une nouvelle cellule, cliquez simplement sur le `+`dans le menu en haut à gauche du notebook (cf. rappels sur les notebooks en bas de ce notebook). Vous pouvez mettre plusieurs lignes de code aussi par cellule.
> Pour executer les cellules, cliquez sur `Shift+Enter`. Executez les dans le bon ordre.
> Remarque: dans un notebook jupyter, l'affichage des vecteurs n'est pas classique. Si vous souhaitez afficher le vecteur de façon plus classique, c'est à dire en ligne avec l'indice pour la 1ère valeur de chaque ligne au début de la ligne, tel qu'il apparait dans R, il est nécessaire d'utiliser la fonction `print()` -> voir dans cet exemple avec un vecteur contenant les deux valeurs numériques 1 et 10.


In [1]:
my_vector <- c(1, 10) # pour générer le vecteur et l'assigner dans un objet "my_vector"
my_vector # l'affichage ici montre deux éléments dont l'affichage est séparé par un point médian.

[1]  1 10

In [2]:
print(my_vector) # L'affichage ici montre le vecteur par ligne avec l'indice 1 entre crochets indiquant l'indice de la première valeur de la ligne.

[1]  1 10


> Vous pouvez également réaliser ces exercices si vous le préférez dans un terminal ou une console de cet environnement `megm1_ue5_r` sur adenine, ou sur la version rstudio de cet environnement.
>
> Il est enfin possible de réaliser ces exercices sur votre ordinateur. Dans ce cas, utilisez un editeur de texte avec coloration syntaxique pour votre code (editeur dans Rstudio, ou Tinn-R ou notepad++ par exemple). Sauvegardez vos commandes dans un fichier mes_commandes.R dans le répertoire de votre choix. Exécutez les commandes une par une dans votre console. Vous pouvez ajouter des commentaires qui ne seront pas éxécutés si vous les précédez du caractère « # ».

>    

---
## Avant d'aller plus loin

<div class="alert alert-block alert-danger"><b>Attention:</b> 
Ne travaillez pas directement sur ce notebook pour ne pas le perdre. Dupliquez-le et renommez-le par exemple en ajoutant vos initiales et travaillez sur cette nouvelle copie. Pour ce faire, dans le panneau de gauche, faites un clic droit sur le fichier et sélectionnez "Duplicate". Puis, toujours dans la colonne de gauche, faites un clic droit sur cette copie et sélectionnez "rename" pour changer le nom. Ouvrez ensuite cette nouvelle version en double cliquant dessus. Vous êtes prêt(e) à démarrer! <br>
<br>
<b>N'oubliez pas de sauvegarder régulièrement votre notebook</b>: <kbd>Ctrl</kbd> + <kbd>S</kbd>. ou en cliquant sur l'icone 💾 en haut à gauche de votre notebook ou dans le Menu du JupyterLab "File puis "Save Notebook"! Vous pouvez aussi le sauvegarder au format html: Menu "File" > Export Notebook As> Export notebook as HTML.
</div>
 

#### 1. Identifiez votre répertoire de travail

In [3]:
getwd()

[1] "/srv/home/cvandiedonck/megm1_ue5_r/R2"

Si ce répertoire ne vous convient pas, changer le pour un répertoire existant `my_directory`par exemple, avec la commande suivante en spécifiant le chemin relatif ou absolu de votre répertoire:
```setwd("path/my_directory")```

#### 2.  Identifiez la version R de votre environnement et packages installés.

In [4]:
sessionInfo()

R version 4.0.5 (2021-03-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /srv/conda/envs/notebook/lib/libopenblasp-r0.3.17.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_0.5.0       digest_0.6.27     utf8_1.2.2        crayon_1.4.1     
 [5] IRdisplay_1.0     repr_1.1.3        lifecycle_1.0.0   jsonlite_1.7.2   
 [9] evaluate_0.14     pillar_1.6.2      rlang_0.4.11      uuid_0.1-4       
[13] vctrs_0.3.8       ellipsis_0.3.2    IRkernel_1.1.1    tools_4

---
---
## Exercice 1

### Execrice 1.1

Créez la matrice identité `matIdentite` de dimension 10 lignes x 10 colonnes contenant uniquement le chiffre 0.

*__Tip :__*
_fonction recommandée : `matrix()`_

In [5]:
matIdentite <- matrix(data = 0, ncol = 10, nrow = 10)

Puis remplacez uniquement les valeurs de la diagonale par le chiffre 1.

*__Tip :__*
_fonction recommandée : `diag()`_



In [6]:
diag(matIdentite) <- 1 #diag() retourne un vecteur dont on peut remplacer les valeurs 0 par 1

Imprimez la matrice à l’écran.

*__Tip :__*
_fonction recommandée : `print()`_

In [7]:
print(matIdentite)

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    1    0    0    0    0    0    0    0    0     0
 [2,]    0    1    0    0    0    0    0    0    0     0
 [3,]    0    0    1    0    0    0    0    0    0     0
 [4,]    0    0    0    1    0    0    0    0    0     0
 [5,]    0    0    0    0    1    0    0    0    0     0
 [6,]    0    0    0    0    0    1    0    0    0     0
 [7,]    0    0    0    0    0    0    1    0    0     0
 [8,]    0    0    0    0    0    0    0    1    0     0
 [9,]    0    0    0    0    0    0    0    0    1     0
[10,]    0    0    0    0    0    0    0    0    0     1


<br>

*__=> Pour aller plus loin :__*
2 variantes plus efficaces pour créer la matrice : 

In [8]:
cat("------variante 1:\n")
diag(1,10,10)

------variante 1:


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 1    0    0    0    0    0    0    0    0    0    
 [2,] 0    1    0    0    0    0    0    0    0    0    
 [3,] 0    0    1    0    0    0    0    0    0    0    
 [4,] 0    0    0    1    0    0    0    0    0    0    
 [5,] 0    0    0    0    1    0    0    0    0    0    
 [6,] 0    0    0    0    0    1    0    0    0    0    
 [7,] 0    0    0    0    0    0    1    0    0    0    
 [8,] 0    0    0    0    0    0    0    1    0    0    
 [9,] 0    0    0    0    0    0    0    0    1    0    
[10,] 0    0    0    0    0    0    0    0    0    1

In [9]:
cat("------variante 2:\n")
diag(10)# en fait, par defaut, si on n'utilise qu'un seul argument dans la fonction diag(), la commande retourne une matrice de 0 sauf pour la diagonale contenant des 1

------variante 2:


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 1    0    0    0    0    0    0    0    0    0    
 [2,] 0    1    0    0    0    0    0    0    0    0    
 [3,] 0    0    1    0    0    0    0    0    0    0    
 [4,] 0    0    0    1    0    0    0    0    0    0    
 [5,] 0    0    0    0    1    0    0    0    0    0    
 [6,] 0    0    0    0    0    1    0    0    0    0    
 [7,] 0    0    0    0    0    0    1    0    0    0    
 [8,] 0    0    0    0    0    0    0    1    0    0    
 [9,] 0    0    0    0    0    0    0    0    1    0    
[10,] 0    0    0    0    0    0    0    0    0    1

---
### Exercice 1.2.

Créez une matrice `matAleatoire` contenant des valeurs tirées aléatoirement de dimension 10 lignes x 10 colonnes, dont les éléments suivent une loi normale de moyenne 0 et de variance 5. 

Imprimez la matrice à l’écran en arrondissant à 2 décimales.

*__Tip :__*
_fonction recommandée : `matrix()`, `print()`, `rnorm()`, `round()`_

In [ ]:
## Generate a 10x10 matrix with random normal numbers
matAleatoire <- matrix(
  nrow = 10, 
  ncol = 10, 
  data = rnorm(n = 100, 
               mean = 0, 
               sd = sqrt(5)))
# as long as you specify the arguments, you may change the order to pass the arguments to the function

In [ ]:
## Print the results rounded at 2 decimals
print(round(matAleatoire, digits = 2))

---
---

## Exercice 2

### Exercice 2.1

Créez deux vecteurs aléatoires nommés `x1` et `x2`, contenant chacun n=10.000 valeurs aléatoires respectivement compatibles:

  - avec une loi normale centrée réduite pour x1;
  - avec une loi uniforme définie sur l’intervalle [0,10] pour x2.

*__Tip :__*
_fonctions recommandées : `rnorm()`, `runif()`_


In [ ]:
n <- 10000 ## define vector sizes => cette étape n'est pas indispensable, vous pouvez directement rentrer la valeur 10000 dans les commandes-ci-dessous

In [ ]:
x1 <- rnorm(n = n, mean = 0, sd = 1) ## normal random
x2 <- runif(n = n, min = 0, max = 10) ## uniform random

<br>

*__=> Pour aller plus loin :__*

On anticipe sur la session sur les figures.
Vérifiez la distribution empirique de ces échantillons en dessinant des histogrammes.

In [ ]:
hist(x = x1, breaks = 100, 
     las = 1, 
     col = "palegreen",
     main = "Random normal numbers",
     xlab = "Value"
     )
cat("+++ distribution normale :\n")
summary(x1)

hist(x = x2, breaks = 10, 
     las = 1, 
     col = "cyan",
     main = "Uniformly distributed random numbers",
     xlab = "Value"
     )
cat("+++ distribution uniforme :\n")
summary(x2)

---
### Exercice 2.2

Créez une matrice `m1` qui contient les 10 premières valeurs de `x1` (colonne 1 de `m1`) et les 10 dernières valeurs de `x2` (colonne 2 de `m1`). Verifiez qu’il s’agit bien d’une matrice et affichez ses dimensions.


*__Tip :__*
_fonction recommandée : `matrix()`, `class()`, `dim()`, `cbind()`,…_


Voici une première solution en créant d'abord une matrice vide:

In [ ]:
## Prepare an empty matrix
m1 <- matrix(nrow = 10, ncol = 2)

## Assign values to the first column
m1[, 1] <- x1[1:10]

## Assign values to the second column
m1[, 2] <- x1[9991:10000]

## Print the result rounded to 3 decimals
print(round(m1, digits = 3))

In [ ]:
## Check it is a matrix and print its dimensions
class(m1)

In [ ]:
print(dim(m1))

<br>

*__=> Pour aller plus loin :__*

On aurait pu aussi assigner les valeurs des colonnes de `m1` à partir des vecteurs `x1` et `x2` en utilisant les fonctions `head()`et `tail()`

In [ ]:
m1[, 1] <- head(x = x1, n = 10) # équivaut à m1[, 1] <- x1[1:10]
m1[, 2] <- tail(x = x1, n = 10) # éqivaut à m1[, 2] <- x1[9991:10000]

---

Cette seconde solution est plus efficace car elle utilise les vecteurs `x1` et `x2` directement avec la fonction `cbind()` sans passer par la création d'une matrice vide.

In [ ]:
m1 <- cbind(x1[1:10], x2[9991:10000])
print(round(m1, digits = 3))

In [ ]:
class(m1)

In [ ]:
print(dim(m1))

---
### Exercice 2.3

Créez une matrice `m2` qui contient

    les 16ème, 51ème, 79ème, 31ème et 27ème valeurs de `x1` (colonne 1 de `m2`) et
    les 30ème, 70ème, 12ème, 49ème et 45ème de `x2` (colonne 2 de `m2`).

Affichez `m2`.

*__Tip :__*
_fonctions recommandées : `matrix()`, `cbind()`, ..._

In [22]:
m2 <- matrix(nrow = 5, ncol = 2)

## Assign values
m2[, 1] <- x1[c(16, 51, 79, 31, 27)]
m2[, 2] <- x2[c(30, 70, 12, 49, 45)]

## Print the result
print(m2)

           [,1]     [,2]
[1,]  0.2913006 3.943023
[2,] -1.3067052 4.046332
[3,]  0.9855518 2.384522
[4,] -0.6181669 5.384409
[5,] -1.3191543 6.418689


In [23]:
## or more directly using the cbind() function without creating an empty matrix first
m2 <- cbind(x1[c(16, 51, 79, 31, 27)], x2[c(30, 70, 12, 49, 45)])
print(m2)

           [,1]     [,2]
[1,]  0.2913006 3.943023
[2,] -1.3067052 4.046332
[3,]  0.9855518 2.384522
[4,] -0.6181669 5.384409
[5,] -1.3191543 6.418689


---
### Exercice 2.4

Concaténez à la suite (l’une en dessous-de l’autre) les matrices `m1` et `m2`, afin d’obtenir une nouvelle matrice `m3`.

Quelles sont les dimensions (nombre de lignes et de colonnes) de `m3` ?


*__Tip :__*
_fonctions recommandées : `rbind()`, `dim()`, `ncol()`, `nrow()`, `str()`_

In [24]:
m3 <- rbind(m1, m2)
print(m3)

            [,1]     [,2]
 [1,] -0.2979710 8.975289
 [2,]  0.4861462 9.941563
 [3,]  0.7798434 5.503638
 [4,] -0.5660618 5.971594
 [5,]  0.8030366 5.532366
 [6,]  0.7221354 7.311653
 [7,] -0.4158272 7.659021
 [8,]  0.4614466 8.025802
 [9,] -0.8530557 8.966842
[10,] -0.5484506 5.922809
[11,]  0.2913006 3.943023
[12,] -1.3067052 4.046332
[13,]  0.9855518 2.384522
[14,] -0.6181669 5.384409
[15,] -1.3191543 6.418689


In [25]:
# alternativement, moins belle, en utilisant matrix, et en emboitant  tout sans creer m1 et m2:
m3 <- matrix(c(x1[1:10], (x2[1:10]),x1[c(16, 51, 79, 31, 27)], (x2[c(30, 70, 12, 49, 45)])),nrow=15, ncol=2, byrow=T)

In [26]:
print(dim(m3))

[1] 15  2


In [27]:
# ou vous pouviez utiliser nrow() et ncol()
nrow(m3)
ncol(m3)

[1] 15

[1] 2

<br>

*__=> Pour aller plus loin :__*

Les operateurs classiques (+, -, * ) font des operations terme à terme si les deux matrices ont la même taille, par exemple: `m1 + rbind(m2,m2)` alors que `m1+m2` retourne une erreur.

Pour faire du calcul matriciel, on utilise un operateur specifique `%*%` pour multiplier. La premiere matrice a autant de lignes qu’il y a de colonnes dans la 2eme matrice. La matrice resultante a autant de lignes que la 1ere matrice et de colonnes que la 2eme matrice.

Quelques exemples:


In [28]:
m4 <- m1 %*% t(m2)# m1 avec la transposée de m2 qui a 2 lignes et 5 colonnes
print(dim(m4))

[1] 10  5


In [29]:
m5 <- m1 %*% t(m1)# m1 avec sa propre tranposée
print(dim(m5))

[1] 10 10


In [30]:
m6 <- t(m1) %*% m1 # ou l'inverse! Pas de commutativite sur ces calculs!
print(dim(m6))

[1] 2 2


---
---

## Exercice 3.1

Importez dans votre session R les données nommées `WorldPhones` (pré-existantes dans R).

Affichez le contenu de la variable `WorldPhones`.

Quelle est sa structure et sa classe ?

*__Tip :__*
_fonctions recommandées : `data(WorldPhones)`, `class()`, `dim()`, `str()`_

In [31]:
data("WorldPhones")

In [32]:
WorldPhones

N.Amer Europe Asia S.Amer Oceania Africa Mid.Amer
1951 45939  21574  2876 1815   1646      89    555    
1956 60423  29990  4708 2568   2366    1411    733    
1957 64721  32510  5230 2695   2526    1546    773    
1958 68484  35218  6662 2845   2691    1663    836    
1959 71799  37598  6856 3000   2868    1769    911    
1960 76036  40341  8220 3145   3054    1905   1008    
1961 79831  43173  9053 3338   3224    2005   1076

In [33]:
class(WorldPhones)

[1] "matrix" "array"

In [34]:
print(dim(WorldPhones))

[1] 7 7


In [35]:
str(WorldPhones)

 num [1:7, 1:7] 45939 60423 64721 68484 71799 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:7] "1951" "1956" "1957" "1958" ...
  ..$ : chr [1:7] "N.Amer" "Europe" "Asia" "S.Amer" ...


---
### Exercice 3.2

Calculez le nombre total de numéros de téléphone attribués :

   - au cours des différentes années (vecteur `nbrTelAn`)
   - pour chaque continent (vecteur `nbrTelCont`)

*__Tip :__*
_fonction recommandée : `sum()`, `apply()`_

In [36]:
# nombre d'appels pour le continent 1
sum(WorldPhones[,1])

[1] 467233

In [37]:
# nombre d'appels pour le continent 2
sum(WorldPhones[,2])

[1] 240404

etc...

*__=> Pour aller plus loin :__*

Pour aller plus rapidement, on utilise la fonction `apply()` qui est très utile pour répéter une commande par ligne ou colonne sur une matrice:


In [38]:
# repetition de la commande sum() en ligne = marginal sums per year
nbrTelAn <- apply(WorldPhones, 1, sum)
print(nbrTelAn)

  1951   1956   1957   1958   1959   1960   1961 
 74494 102199 110001 118399 124801 133709 141700 


In [39]:
# repetition de la commande sum() en colonne =  marginal sums per continent
nbrTelCont <- apply(WorldPhones, 2, sum)
print(nbrTelCont)

  N.Amer   Europe     Asia   S.Amer  Oceania   Africa Mid.Amer 
  467233   240404    43605    19406    18375    10388     5892 


---
### Exercice 3.3

Quel est le continent qui a le plus / moins de numéros attribués ?


*__Tip :__*
_fonctions recommandées : `names()`, `which()`, `max()`, `min()`, `which.max()`, `which.min()`_

In [40]:
# continent avec le plus de numeros
names(nbrTelCont)[which(nbrTelCont == max(nbrTelCont))]

[1] "N.Amer"

In [41]:
# continent avec le moins de numeros
names(nbrTelCont)[which(nbrTelCont == min(nbrTelCont))]

[1] "Mid.Amer"

In [42]:
# ou plus simplement avec la commande which.max() ou which.min()
names(which.max(nbrTelCont))

[1] "N.Amer"

In [43]:
names(which.min(nbrTelCont))

[1] "Mid.Amer"

<br>

*__=> Pour aller plus loin :__*

Une autre façon en utilisant les fonctions `tail()`et `head()` après avoir trié les comptes avec `sort()`



In [44]:
tail(sort(nbrTelCont), n = 1)

N.Amer 
467233

---
### Exercice 3.4

Dans combien de continents y a-t-il plus de : 20.000, 50.000 et 200.000 numéros de téléphone attribués ?

*__Tip :__*
_fonctions recommandées : `sum()`_

In [45]:
cat("Il y a plus de 20 000 numéros attribués dans", sum(nbrTelCont > 20000), "continents. \n") # la phrase n'était pas demandée dans l'exrecice.
cat("Il y a plus de 50 000 numéros attribués dans", sum(nbrTelCont > 50000), "continents. \n")
cat("Il y a plus de 200 000 numéros attribués dans", sum(nbrTelCont > 200000), "continents. \n")

Il y a plus de 20 000 numéros attribués dans 3 continents. 
Il y a plus de 50 000 numéros attribués dans 2 continents. 
Il y a plus de 200 000 numéros attribués dans 2 continents. 


---
A la fin, je sauve la liste comme objet pour de futures sessions dans R.

In [46]:
ls()
save.image(file="R2_practice.RData")

[1] "m1"           "m2"           "m3"           "m4"           "m5"          
 [6] "m6"           "matAleatoire" "matIdentite"  "my_vector"    "n"           
[11] "nbrTelAn"     "nbrTelCont"   "WorldPhones"  "x1"           "x2"

***
***
## Useful commands
<div class="alert alert-block alert-info"> 
    
- <kbd>CTRL</kbd>+<kbd>S</kbd> : save notebook<br>    
- <kbd>CTRL</kbd>+<kbd>ENTER</kbd> : Run Cell<br>  
- <kbd>SHIFT</kbd>+<kbd>ENTER</kbd> : Run Cell and Select Next<br>   
- <kbd>ALT</kbd>+<kbd>ENTER</kbd> : Run Cell and Insert Below<br>   
- <kbd>ESC</kbd>+<kbd>y</kbd> : Change to *Code* Cell Type<br>  
- <kbd>ESC</kbd>+<kbd>m</kbd> : Change to *Markdown* Cell Type<br> 
- <kbd>ESC</kbd>+<kbd>r</kbd> : Change to *Raw* Cell Type<br>    
- <kbd>ESC</kbd>+<kbd>a</kbd> : Create Cell Above<br> 
- <kbd>ESC</kbd>+<kbd>b</kbd> : Create Cell Below<br> 

<em>  
To make nice html reports with markdown: <a href="https://dillinger.io/" title="dillinger.io">html visualization tool 1</a> or <a href="https://stackedit.io/app#" title="stackedit.io">html visualization tool 2</a>, <a href="https://www.tablesgenerator.com/markdown_tables" title="tablesgenerator.com">to draw nice tables</a>, and the <a href="https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd" title="Ultimate guide">Ultimate guide</a>. <br>
Further reading on JupyterLab notebooks: <a href="https://jupyterlab.readthedocs.io/en/latest/user/notebook.html" title="Jupyter Lab">Jupyter Lab documentation</a>.<br>   
</em>    
 
</div>

---
---

## <mark>Check list des actions avant la prochaine session R:<mark>

_Pour cocher les cases, ouvrez la cellule du notebook et remplacez l'espace entre les crochets par un `x` lorsque l'action est effectuée_

[ ] relire le cours et revoir les différents supports dont diapos, vidéos, scripts et notebooks
            
[ ] faire les exercices sans les corrections

[ ] lire et comprendre les corrections

[ ] refaire les exercices sans les corrections
    
[ ] étudier le tutorial sur les facteurs (.html sur moodle)
    
[ ] continuer les tuto de swirl 1, 3 à 6  à votre rythme pour les avoir finis avant le QCM. 